-- 1.CURRENT_DATE/ CURDATE
select current_date();
select curdate();

-- 2.CURRENT_TIME/CURTME
SELECT current_time();
SELECT curtime();

-- 3.NOW()/CURRENT_TIMESTAMP
SELECT NOW();
SELECT CURRENT_TIMESTAMP();

-- 4.DATE()
SELECT DATE('2026-02-12');

-- 5. TIME()
SELECT TIME('2025-09-23 15:45:00');

-- 6. YEAR(), MONTH(), DAY()
SELECT YEAR(NOW());
SELECT MONTH(NOW());
SELECT DAY(NOW());

-- 7. DAYAME(), MONTHNAME()
SELECT DAYNAME(NOW());
SELECT MONTHNAME(NOW());

-- 8. DATE_ADD()/ADDDATE()
-- UNITS: SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, QUARTER, YEAR
SELECT DATE_ADD(NOW(), INTERVAL 20 DAY);
select ADDDATE(NOW(),INTERVAL 2 MONTH);

-- 9. DATE_SUB
SELECT DATE_SUB(NOW(), INTERVAL 20 DAY);

-- 10. DATEDIFF()
SELECT DATEDIFF(NOW(), '2026-09-12');

-- 11.TIMEDIFF()
SELECT timediff('10:30:00','09:15:00');

-- 12. STR_TO_DATE()
SELECT str_to_date('2026-03-30','%y-%m-%d');

-- 13. DATE_FORMAT()
SELECT DATE_FORMAT('2025-09-23','%W %M %Y');
SELECT DATE_FORMAT(NOW(),'%D-%M-%Y %H:%I:%S');