-- 1. CHAR_LENGTH(STR) OR CHARACTER_LENGTH(STR)
SELECT char_length('HELLO');
SELECT char_length('😁');

-- 2. CONCAT(STR1,STR2,...)
SELECT concat('MY','SQL');
SELECT concat('PYTHON',' ', 'PROGRAMMING', 'LANG' );

-- 3. CONCAT_WS(SEPATOR, STR1,STR2,.....)
SELECT CONCAT_WS('-', '2025', '09', '23');

-- 4. UPPER(STR)
SELECT upper('Hello');

-- 5.LOWER(STR)/LCASE(STR)
SELECT LOWER('HELLO');

-- 6.LEFT(STR, LEN)
SELECT LEFT("DATABASE",5);


-- 7. RIGHT(STR, LEN)
SELECT RIGHT("DATABASE",3);

-- 8. SUBSTRING(STR, START, LENGTH)
SELECT substring('DATABASE',5);
SELECT SUBSTRING('PYTHON PROGRAMMING LANG', 10, 7);
 
-- 9. LOCATE(SUBSTR, STR)
SELECT LOCATE('A', 'DATABSE');

-- 10. REPLACE(STR, FROM_STR, TO_STR)
SELECT REPLACE('XXXXXXXXXXXXHELLOXXX', 'X', '');

-- 11. TRIM([LEADING | TRAILING | BOTH] REMSTR FROM STR)
SELECT TRIM('HELLO     WORLD');

-- 12.LTRIM(STR)
SELECT LTRIM('  HELLO');

-- 13.RTRIM(STR)
SELECT RTRIM('HELLO    ');

-- 14. REVERSE(STR)
SELECT reverse('MYSQL');

-- 15.LPAD(STR, LEN, PADSTR)
SELECT LPAD('1234', '10', '-');

-- 16. RPAD(STR, LEN, PADSTR)
SELECT RPAD('123', '8', '*');

-- 17. REPEAT(STR, COUNT)
SELECT repeat('MYSQL-', 3);
